import { Product } from './types';

export const products: Product[] = [
    {
        id: '1',
        name: 'Le Beau Le Parfum',
        brand: 'Jean Paul Gaultier',
        slug: 'le-beau-le-parfum',
        description: 'Una interpretación intensa y adictiva de la naturaleza original de Le Beau. Notas de coco, piña, sándalo y haba tonka.',
        image: 'https://i.imgur.com/a04sjov.png',
        notes: ['Piña', 'Iris', 'Ciprés', 'Haba Tonka', 'Coco'],
        prices: { 3: 150, 5: 240, 10: 450 },
        isFeatured: true,
    },
    {
        id: '2',
        name: 'Paradise Garden',
        brand: 'Jean Paul Gaultier',
        slug: 'paradise-garden',
        description: 'Un jardín de tentaciones. Frescura verde y acuática con un toque dulce y exótico.',
        image: 'https://i.imgur.com/gyjNwAp.jpeg',
        notes: ['Menta', 'Hierba Verde', 'Coco', 'Sándalo'],
        prices: { 3: 160, 5: 250, 10: 460 },
    },
    {
        id: '3',
        name: 'Le Male Elixir',
        brand: 'Jean Paul Gaultier',
        slug: 'le-male-elixir',
        description: 'Un perfume ardiente y sensual. Lavanda dorada y miel sobre un fondo de tabaco y haba tonka.',
        image: 'https://i.imgur.com/PTemlE2.jpeg',
        notes: ['Lavanda', 'Miel', 'Tabaco', 'Haba Tonka'],
        prices: { 3: 170, 5: 270, 10: 480 },
        isFeatured: true,
    },
    {
        id: '4',
        name: 'Born in Roma Intense',
        brand: 'Valentino',
        slug: 'born-in-roma-intense',
        description: 'Una celebración de la Roma nocturna. Vainilla bourbon y notas ambarinas.',
        image: 'https://i.imgur.com/ASBcINI.jpeg',
        notes: ['Vainilla', 'Lavanda', 'Vetiver'],
        prices: { 3: 160, 5: 250, 10: 460 },
    },
    {
        id: '5',
        name: 'Y Eau de Parfum',
        brand: 'YSL',
        slug: 'y-eau-de-parfum',
        description: 'La fragancia de los hombres que se atreven. Frescura aromática con un fondo amaderado profundo.',
        image: 'https://i.imgur.com/ObxsEAp.jpeg',
        notes: ['Manzana', 'Jengibre', 'Salvia', 'Geranio'],
        prices: { 3: 140, 5: 220, 10: 400 },
    },
    {
        id: '6',
        name: 'Scandal Le Parfum',
        brand: 'Jean Paul Gaultier',
        slug: 'scandal-le-parfum',
        description: 'Un golpe de teatro. Geranio intenso y caramelo tostado.',
        image: 'https://i.imgur.com/D4NX1DB.jpeg',
        notes: ['Geranio', 'Haba Tonka', 'Sándalo'],
        prices: { 3: 150, 5: 240, 10: 440 },
    },
    {
        id: '7',
        name: 'Odyssey Aqua',
        brand: 'Armaf',
        slug: 'odyssey-aqua',
        description: 'Frescura marina estimulante con un toque de elegancia moderna.',
        image: 'https://i.imgur.com/1riqqdz.jpeg',
        notes: ['Notas Marinas', 'Cítricos', 'Maderas'],
        prices: { 3: 80, 5: 120, 10: 200 },
    },
    {
        id: '8',
        name: 'Liquid Brun',
        brand: 'French Avenue',
        slug: 'liquid-brun',
        description: 'Una fragancia sofisticada y envolvente, ideal para ocasiones especiales.',
        image: 'https://i.imgur.com/P1RrbQJ.jpeg',
        notes: ['Especias', 'Maderas', 'Ámbar'],
        prices: { 3: 90, 5: 140, 10: 250 },
    },
    {
        id: '9',
        name: 'Hawas Fire',
        brand: 'Rasasi',
        slug: 'hawas-fire',
        description: 'La contraparte ardiente de Hawas, con notas cálidas y vibrantes.',
        image: 'https://i.imgur.com/OlDTK2q.jpeg',
        notes: ['Cítricos', 'Especias', 'Almizcle'],
        prices: { 3: 100, 5: 160, 10: 280 },
    },
    {
        id: '10',
        name: 'Khamrah Qahwa',
        brand: 'Lattafa',
        slug: 'khamrah-qahwa',
        description: 'Una versión rica y gourmand del clásico Khamrah con notas de café intenso.',
        image: 'https://i.imgur.com/O9uMmri.jpeg',
        notes: ['Café', 'Canela', 'Cardamomo', 'Praliné'],
        prices: { 3: 90, 5: 140, 10: 250 },
    },
    {
        id: '11',
        name: 'Hawas Ice',
        brand: 'Rasasi',
        slug: 'hawas-ice',
        description: 'Frescura helada y frutal, perfecta para el calor intenso.',
        image: 'https://i.imgur.com/rjX630d.jpeg',
        notes: ['Manzana', 'Ciruela', 'Cítricos', 'Notas Acuáticas'],
        prices: { 3: 110, 5: 180, 10: 320 },
    },
    {
        id: '12',
        name: 'Urban Man Elixir',
        brand: 'Armaf',
        slug: 'urban-man-elixir',
        description: 'Urbano, moderno y magnético. Para el hombre cosmopolita.',
        image: 'https://i.imgur.com/iiozczK.jpeg',
        notes: ['Pimienta Rosa', 'Jazmín', 'Lavanda', 'Pachulí'],
        prices: { 3: 90, 5: 130, 10: 220 },
    },
    {
        id: '13',
        name: 'Yara',
        brand: 'Lattafa',
        slug: 'yara',
        description: 'Dulce, cremoso y femenino. Un aroma viral que encanta.',
        image: 'https://i.imgur.com/EwFVkSR.jpeg',
        notes: ['Orquídea', 'Vainilla', 'Frutas Tropicales'],
        prices: { 3: 80, 5: 120, 10: 200 },
    },
    {
        id: '14',
        name: 'Turathi Blue',
        brand: 'Afnan',
        slug: 'turathi-blue',
        description: 'Cítrico y sofisticado, una joya oculta de la perfumería árabe.',
        image: 'https://i.imgur.com/zndPWI4.png',
        notes: ['Cítricos', 'Ámbar', 'Almizcle', 'Especias'],
        prices: { 3: 90, 5: 140, 10: 240 },
    },
    {
        id: '15',
        name: 'Odyssey White',
        brand: 'Armaf',
        slug: 'odyssey-white',
        description: 'Elegancia pura en una botella. Fresco y versátil.',
        image: 'https://i.imgur.com/RuUAG56.jpeg',
        notes: ['Bergamota', 'Lavanda', 'Maderas Blancas'],
        prices: { 3: 80, 5: 120, 10: 200 },
    },
    {
        id: '16',
        name: 'Honor & Glory',
        brand: 'Lattafa',
        slug: 'honor-and-glory',
        description: 'Una fragancia majestuosa con una apertura única de piña brulee.',
        image: 'https://i.imgur.com/Saa1zb1.jpeg',
        notes: ['Piña', 'Crème Brûlée', 'Cúrcuma', 'Sándalo'],
        prices: { 3: 90, 5: 150, 10: 260 },
    },
    {
        id: '17',
        name: 'Sceptre Malachite',
        brand: 'Maison Alhambra',
        slug: 'sceptre-malachite',
        description: 'Inspirado en gemas preciosas, un aroma verde y amaderado.',
        image: 'https://i.imgur.com/J5S486o.jpeg',
        notes: ['Notas Verdes', 'Maderas', 'Ámbar'],
        prices: { 3: 100, 5: 160, 10: 280 },
    },
    {
        id: '18',
        name: 'Jasoor',
        brand: 'Lattafa',
        slug: 'jasoor',
        description: 'Potente y distintivo, para dejar huella.',
        image: 'https://i.imgur.com/LDb4XC9.jpeg',
        notes: ['Manzana', 'Cardamomo', 'Tabaco'],
        prices: { 3: 85, 5: 130, 10: 220 },
    },
    {
        id: '19',
        name: 'Odyssey Montagne',
        brand: 'Armaf',
        slug: 'odyssey-montagne',
        description: 'Fresco y vigorizante, inspirado en el aire de montaña.',
        image: 'https://i.imgur.com/09ZM78B.jpeg',
        notes: ['Cítricos', 'Maderas', 'Notas Ozónicas'],
        prices: { 3: 80, 5: 120, 10: 200 },
    },
    {
        id: '20',
        name: 'Hayaati',
        brand: 'Lattafa',
        slug: 'hayaati',
        description: 'La esencia de la vida. Frutal, fresco y ligeramente dulce.',
        image: 'https://i.imgur.com/3IpcVvF.jpeg',
        notes: ['Manzana', 'Bergamota', 'Canela', 'Vainilla'],
        prices: { 3: 70, 5: 100, 10: 180 },
    },
    {
        id: '21',
        name: 'Fakhar Black',
        brand: 'Lattafa',
        slug: 'fakhar-black',
        description: 'El clon perfecto de YSL Y. Versátil y cumplidor.',
        image: 'https://i.imgur.com/M6fEBWT.jpeg',
        notes: ['Manzana', 'Jengibre', 'Lavanda', 'Haba Tonka'],
        prices: { 3: 80, 5: 130, 10: 220 },
    },
    {
        id: '22',
        name: 'Now Woman',
        brand: 'Rave',
        slug: 'now-woman',
        description: 'Una explosión de frutos rojos y malvavisco. Irresistible.',
        image: 'https://i.imgur.com/bpuLdEk.jpeg',
        notes: ['Frutos Rojos', 'Malvavisco', 'Vainilla'],
        prices: { 3: 75, 5: 110, 10: 190 },
    },
    {
        id: '23',
        name: 'Atlas',
        brand: 'Lattafa',
        slug: 'atlas',
        description: 'Inspirado en Megamare. Potencia marina extrema.',
        image: 'https://i.imgur.com/KZa6jBa.jpeg',
        notes: ['Notas Marinas', 'Algas', 'Almizcle', 'Limón'],
        prices: { 3: 100, 5: 160, 10: 280 },
    },
];
